import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "pt-[80px] px-2 sm:px-5 xl:px-10 h-full")}>
        <Header />
        <div className="max-w-screen-xl h-full mx-auto px-3 sm:px-5 lg:px-10">
          {children}
        </div>
      </body>
    </html>
  );
}
